#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

[[ -n "$YEAR"     ]] || YEAR="$(date +%Y)"
[[ -n "$MONTH"    ]] || MONTH="$(date +%m)"
[[ -n "$CALENDAR" ]] || CALENDAR="$HOME/.calendar"
[[ -e '.calendar' ]] && CALENDAR="$PWD/.calendar"
[[ -z "$1"        ]] || MONTH="$1"
[[ -z "$2"        ]] || YEAR="$2"
[[ -z "$3"        ]] || CALENDAR="$3"

for bin in pcal ps2pdf zathura
do
  if ! command -v $bin >/dev/null
  then
    echo "NOT FOUNT $bin"
    exit 1
  fi
done

TMP="$(mktemp --suffix .tmp)"
PS="$(mktemp --suffix .ps)"
PDF="$(mktemp --suffix .pdf)"

sed 's/\ \+/ /g' "$CALENDAR" \
  | grep -v '^#'             \
  | grep -v '^$'             \
  | while read -r LINE
do

  F=$(echo "$LINE" | awk '{print $1}')

  case "$F" in
    even|all)
      echo "$LINE"
      ;;
    *)
      echo "$LINE" | cut -c -35 | sed 's/#.*//g'
      ;;
  esac

done | sort -k1,2 | bullet2ascii > "$TMP"

[[ -n "$CAL_DEBUG" ]] && cat -n "$TMP"

pcal                \
  -B                \
  -P A4             \
  -S                \
  -a "${LANG%_*}"   \
  -d Inconsolata/12 \
  -f "$TMP"         \
  -n Inconsolata/6  \
  -s 1.0:0.0:0.0    \
  -t Inconsolata/10 \
  "$MONTH"          \
  "$YEAR"           > "$PS" && ps2pdf "$PS" "$PDF"

# set zathura as default pdf viewver
# xdg-mime default org.pwmt.zathura.desktop application/pdf

if [[ -n "$DISPLAY" ]]
then
  if xdg-mime query default application/pdf >/dev/null
  then
    xdg-open "$PDF"
  fi
else
  echo "$PDF"
fi
