#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2021 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

MSG=''

[[ -n "$DATE" ]] || DATE="$(date +%F)"
[[ -n "$DAYS" ]] || DAYS=30
[[ -z "$1"    ]] || DAYS="$1"
[[ -z "$2"    ]] || DATE="$2"
[[ -z "$3"    ]] || MSG=" $3"

for D in $(seq 0 "$DAYS")
do
  ISO="$(date -d "$DATE + $D days" +'%F')"
  MONTH="$(LC_ALL=en_US.UTF-8 date -d "$DATE + $D days" +'%b')"
  DAY="$(date -d "$DATE + $D days" +'%d')"
  printf "%s %s%s\\n" "$ISO" "${MONTH^} $DAY" "$MSG"
done
