#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2023 Osiris Alejandro Gomez <osiux@osiux.com>
# Copyright (C) 2023 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

function die()
{
  echo >&2 "$1"
  exit 1
}

if [[ ! -t 0 ]]
then
  TMPI="$(mktemp)"

  true > "$TMPI"

  while IFS= read -r PIPED_INPUT
  do
    echo "$PIPED_INPUT" >> "$TMPI"
  done

fi

[[ -e "$TMPI"         ]] || die "NOT FOUND FILE $TMPI"
[[ -n "$CALENDAR"     ]] || CALENDAR="$HOME/.calendar"
[[ -e '.calendar'     ]] && CALENDAR="$PWD/.calendar"
[[ -e "$CALENDAR"     ]] || die "NOT FOUND $CALENDAR"
[[ -z "$1"            ]] || JRNL="$1"
[[ -n "$REGEX_DATE"   ]] || REGEX_DATE='[0-9]{4}-[0-9]{2}-[0-9]{2}'
[[ -n "$JRNL"         ]] && DATE="$(echo "$JRNL" | grep -Eo "$REGEX_DATE")"
[[ -n "$DATE"         ]] || DATE="$(date +%F)"

CALDAY="$(LC_ALL=c date +'%b %d' -d "$DATE")"
CALDAY="${CALDAY^}"

while read -r LINE
do

  if [[ "$JRNL" = "$CALENDAR" ]]
  then
    TODO="$(echo "$LINE" | tr '/' '_')"
    DONE="$(echo "$LINE" | tr '_' '/' | tr '×' '·')"
  else
    TODO="$CALDAY $(echo "$LINE" | tr '/' '_')"
    DONE="$CALDAY $(echo "$LINE" | tr '_' '/' | tr '×' '·')"
    sed -i --follow-symlinks "s/$TODO/$DONE/g" "$CALENDAR"
  fi

  echo "${LINE//×/·}"

done < "$TMPI"
