#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

ITEMS=$(cat << EOF
all
Jan
Feb
Mar
Apr
May
Jun
Jul
Aug
Sep
Oct
Nov
Dec
EOF
)

[[ -n "$CALENDAR" ]] || CALENDAR="$HOME/.calendar"
[[ -e '.calendar' ]] && CALENDAR="$PWD/.calendar"
[[ -z "$1"        ]] || CALENDAR="$1"
[[ -e "$CALENDAR" ]] || exit 1

TMP="$(mktemp)"

echo "$ITEMS" | while read -r ITEM
do

  echo "## $ITEM"
  grep -i "^$ITEM" "$CAL" | sort -k2

done | awk '!seen[$1$2$3$4$5]++' > "$TMP" && mv -f "$TMP" "$CALENDAR"
