#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2019 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC2086

function die()
{
  echo >&2 "$1"
  exit 1
}

[[ -n "$YEAR"     ]] || YEAR="$(date +%Y)"
[[ -z "$2"        ]] || YEAR="$2"
[[ -n "$MONTH"    ]] || MONTH="$(date +%m)"
[[ -z "$1"        ]] || MONTH="$(printf "%02d" "$1")"
[[ -n "$DAY"      ]] || DAY='01'
[[ -n "$CALENDAR" ]] || CALENDAR="$HOME/.calendar"
[[ -e '.calendar' ]] && CALENDAR="$PWD/.calendar"
[[ -e "$CALENDAR" ]] || die "NOT FOUND .calendar"
[[ -n "$M"        ]] || M="${MONTH##0*}"
[[ -n "$DIR"      ]] || DIR="$HOME/.jrnl"
[[ -d "$DIR"      ]] || mkdir -p "$DIR/$YEAR"
[[ -n "$JRNL"     ]] || JRNL="$DIR/$YEAR/$MONTH.jrnl"
[[ -n "$MONTHS"   ]] || MONTHS="$DIR/$YEAR/months.jrnl"
[[ -n "$VIM"      ]] || VIM="$(which vim)"

caljmonth "$MONTH" "$YEAR" > "$JRNL"

MM="${MONTH##*0}"
DIFF=3
FILES="$JRNL "

for i in $(seq 1 $DIFF)
do
  MM="$(printf "%02d" "$((MONTH + i))")"
  JRNL="$DIR/$YEAR/$MM.jrnl"
  # FIXME ADD CACHE [[ -e "$JRNL" ]] ||
  caljmonth "$MM" "$YEAR"
  FILES+="$JRNL "
done

paste -d '  ' $FILES | bullet2ascii > "$MONTHS"

$VIM -O $FILES
