#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2019 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

[[ -n "$YEAR"     ]] || YEAR="$(date +%Y)"
[[ -n "$MONTH"    ]] || MONTH="$(date +%m)"
[[ -n "$DAY"      ]] || DAY="$(date +%e)"
[[ -n "$CALENDAR" ]] || CALENDAR="$HOME/.calendar"
[[ -e '.calendar' ]] && CALENDAR="$PWD/.calendar"
[[ -e "$CALENDAR" ]] || exit 1

DAY="${DAY/ /}"

DAYS="$(for i in {1..7};do date -d "+$i day" +%d;done \
  | tr '\n' '|' \
  | sed 's/|$//g')"

[[ "$DAY" -gt 28 ]] && MONTH="$(date +%m -d '+1 week')"

REGEX="$MONTH/($DAYS)"
printf "%s %s\n" "$(date +%F)" 'TODAY'

pcal -f "$CALENDAR" -c "$YEAR" \
  | grep -iE "$REGEX" \
  | while read -r D REMINDER
    do
      DAY="$(date --date="$YEAR/$D" +%F)"
      printf "%s %s\n" "$DAY" "$REMINDER"
    done
